receivers:
  otlp:
    protocols:
      grpc:
  zipkin:
    endpoint: "0.0.0.0:9411"

exporters:
  debug:
    verbosity: detailed
  logging:
    loglevel: debug
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
  prometheus:
    endpoint: "0.0.0.0:9464"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
#  zipkin:
#    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
#    format: proto
#  jaeger:
#    endpoint: jaeger-all-in-one:14250
#    tls:
#      insecure: true

processors:
  batch:
    send_batch_size: 1

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
      #exporters: [debug]
    traces:
      receivers: [otlp, zipkin]
      processors: [batch]
#      exporters: [jaeger,zipkin,otlp]
      exporters: [debug, otlp/tempo]
      #exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug, loki]
      #exporters: [debug]