info:
  app:
    description: '@project.description@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    name: '@project.name@'
    version: '@project.version@'

logging:
  level:
    org:
      c4rth: INFO
      springframework:
        cloud:
          sleuth: TRACE
        web: DEBUG
  #  io: TRACE
  pattern:
    # Logging pattern containing traceId and spanId; no longer provided through Sleuth by default
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    configprops:
      show-values: always
    env:
      show-values: always
  metrics:
    # Exemplar metrics
    distribution:
      percentiles-histogram:
        http.server.requests: true
      minimum-expected-value:
        http.server.requests: 5ms
      maximum-expected-value:
        http.server.requests: 1000ms
    tags:
      application: ${spring.application.name}
  prometheus.metrics.export.enabled: true

spring:
  application:
    name: organization-service
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:organizationdb
    username: sa
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  #  properties:
  #    hibernate:
  #      dialect: org.hibernate.dialect.H2Dialect
  zipkin:
    baseUrl: http://localhost:9411
    service:
      name: ${spring.application.name}
  threads:
    virtual:
      enabled: true

management.tracing.propagation.type: b3

management.tracing.sampling.probability: 1.0
